export type WzorCV = {
  slug: string
  icon: string
  title: string
  titleGen: string  // genitive: "CV programisty"
  intro: string
  shouldContain: string[]
  example: {
    name: string
    position: string
    summary: string
    experience: { position: string; company: string; dates: string; bullets: string[] }[]
    skills: string[]
  }
  tips: string[]
  faqs: { q: string; a: string }[]
}

export const WZORY: WzorCV[] = [
  {
    slug: 'programista',
    icon: '💻',
    title: 'CV programisty',
    titleGen: 'CV programisty',
    intro: 'CV programisty musi w kilka sekund pokazać Twój stack technologiczny, realne projekty i wpływ na produkt. Rekruterzy IT skanują CV pod kątem konkretnych technologii — dlatego liczą się fakty, liczby i czytelna struktura.',
    shouldContain: [
      'Dane kontaktowe oraz linki do GitHub i portfolio',
      'Krótkie podsumowanie zawodowe (2–3 zdania)',
      'Umiejętności techniczne: języki, frameworki, narzędzia',
      'Doświadczenie opisane przez konkretne projekty i efekty',
      'Wykształcenie, kursy i certyfikaty',
      'Poziom znajomości języka angielskiego',
    ],
    example: {
      name: 'Jan Kowalski',
      position: 'Frontend Developer',
      summary: 'Programista z 4-letnim doświadczeniem w tworzeniu aplikacji webowych w React i Node.js. Dostarczam wydajny, testowalny kod i dbam o jakość produktu oraz doświadczenie użytkownika.',
      experience: [{
        position: 'Frontend Developer',
        company: 'Software House',
        dates: '2022 – obecnie',
        bullets: [
          'Zbudowałem interfejs aplikacji SaaS w React, z której korzysta ponad 15 000 użytkowników',
          'Skróciłem czas ładowania aplikacji o 40% dzięki optymalizacji bundla i lazy loadingowi',
          'Wdrożyłem testy jednostkowe (Jest), zwiększając pokrycie kodu do 85%',
        ],
      }],
      skills: ['JavaScript', 'TypeScript', 'React', 'Node.js', 'SQL', 'Git', 'Docker', 'REST API', 'Agile/Scrum'],
    },
    tips: [
      'Podaj aktywne linki do GitHub i portfolio — rekruter chce zobaczyć kod.',
      'Opisuj osiągnięcia liczbami (wydajność, liczba użytkowników, pokrycie testami).',
      'Dopasuj listę technologii do konkretnej oferty pracy.',
      'Nie wymieniaj wszystkich technologii świata — wybierz te, które znasz dobrze.',
      'Dodaj sekcję projektów, jeśli masz krótkie doświadczenie zawodowe.',
    ],
    faqs: [
      { q: 'Czy CV programisty potrzebuje zdjęcia?', a: 'Zdjęcie nie jest wymagane i w branży IT bywa pomijane. Liczą się umiejętności i projekty — zdjęcie dodaj, jeśli czujesz, że wzmacnia profesjonalny wizerunek.' },
      { q: 'Jak długie powinno być CV programisty?', a: 'Najlepiej jedna strona przy doświadczeniu do ~5 lat. Przy bogatym doświadczeniu maksymalnie dwie strony — bez wodolejstwa.' },
    ],
  },
  {
    slug: 'ksiegowa',
    icon: '📊',
    title: 'CV księgowej',
    titleGen: 'CV księgowej',
    intro: 'CV księgowej powinno podkreślać precyzję, znajomość przepisów podatkowych i doświadczenie z systemami finansowymi. Rekruterzy szukają konkretnych umiejętności i zakresu obsługiwanych dokumentów.',
    shouldContain: [
      'Doświadczenie z systemami finansowo-księgowymi (Symfonia, SAP, Comarch)',
      'Znajomość przepisów podatkowych i prawa bilansowego',
      'Obsługiwane dokumenty: faktury, deklaracje VAT, PIT, bilanse',
      'Umiejętności MS Excel i arkuszy kalkulacyjnych',
      'Certyfikaty i kursy z rachunkowości',
    ],
    example: {
      name: 'Anna Nowak',
      position: 'Główna Księgowa',
      summary: 'Doświadczona księgowa z 7-letnim stażem w prowadzeniu pełnej księgowości dla firm MŚP. Sprawnie obsługuję systemy Comarch ERP i Symfonia, dbam o terminowe rozliczenia podatkowe.',
      experience: [{
        position: 'Główna Księgowa',
        company: 'Firma XYZ Sp. z o.o.',
        dates: '2019 – obecnie',
        bullets: [
          'Prowadzę pełną księgowość dla 3 spółek z grupy kapitałowej (łącznie 200+ pracowników)',
          'Przygotowuję miesięczne deklaracje VAT, PIT i sprawozdania finansowe',
          'Wdrożyłam automatyzację raportowania w Comarch ERP, skracając czas przygotowania raportów o 30%',
        ],
      }],
      skills: ['Comarch ERP', 'Symfonia', 'VAT', 'PIT', 'CIT', 'MS Excel', 'Prawo bilansowe', 'MSSF'],
    },
    tips: [
      'Wymień konkretne systemy księgowe, z których korzystasz.',
      'Podkreśl skalę obsługiwanej firmy (liczba pracowników, przychody).',
      'Wspomnij o terminowości i bezbłędnym prowadzeniu dokumentacji.',
      'Certyfikat z rachunkowości znacznie zwiększa atrakcyjność CV.',
    ],
    faqs: [
      { q: 'Co wyróżnia dobre CV księgowej?', a: 'Konkretne systemy, znajomość aktualnych przepisów i mierzalne osiągnięcia — np. liczba obsługiwanych firm lub skala dokumentacji.' },
    ],
  },
  {
    slug: 'specjalista-ds-marketingu',
    icon: '📣',
    title: 'CV specjalisty ds. marketingu',
    titleGen: 'CV specjalisty ds. marketingu',
    intro: 'CV marketera musi pokazać efekty kampanii liczbami i znajomość narzędzi cyfrowych. Rekruterzy szukają osób, które potrafią mierzyć wyniki i optymalizować działania.',
    shouldContain: [
      'Narzędzia: Google Ads, Meta Ads, GA4, HubSpot, Mailchimp',
      'Wyniki kampanii: ROAS, CTR, konwersje, koszt pozyskania klienta',
      'Zarządzanie budżetem reklamowym',
      'Social media i content marketing',
      'SEO / SEM',
    ],
    example: {
      name: 'Marta Wiśniewska',
      position: 'Performance Marketing Specialist',
      summary: 'Specjalista performance marketingu z 3-letnim doświadczeniem w prowadzeniu kampanii Google Ads i Meta Ads. Zarządzałam budżetami powyżej 100 000 PLN miesięcznie i konsekwentnie osiągałam ROAS na poziomie 400%.',
      experience: [{
        position: 'Performance Marketing Specialist',
        company: 'Agencja Cyfrowa ABC',
        dates: '2021 – obecnie',
        bullets: [
          'Zarządzam budżetem reklamowym 120 000 PLN/mies. dla 8 klientów e-commerce',
          'Osiągnęłam średni ROAS 420% w kampaniach Google Shopping',
          'Zredukowałam koszt pozyskania klienta (CAC) o 25% dzięki optymalizacji grup odbiorców',
        ],
      }],
      skills: ['Google Ads', 'Meta Ads', 'GA4', 'HubSpot', 'SEO', 'Content Marketing', 'Mailchimp', 'Canva'],
    },
    tips: [
      'Podawaj wyniki kampanii w liczbach (ROAS, CTR, współczynnik konwersji).',
      'Wymień narzędzia, które naprawdę znasz — to weryfikowalne.',
      'Pokaż doświadczenie w zarządzaniu budżetem reklamowym.',
      'Dodaj link do portfolio lub case study, jeśli możesz.',
    ],
    faqs: [
      { q: 'Czy warto dołączyć portfolio do CV marketera?', a: 'Zdecydowanie tak. Case study z wynikami kampanii to najlepsza wizytówka i wyróżnik wśród kandydatów.' },
    ],
  },
  {
    slug: 'kierowca',
    icon: '🚚',
    title: 'CV kierowcy',
    titleGen: 'CV kierowcy',
    intro: 'CV kierowcy powinno jasno pokazać posiadane uprawnienia, rodzaj obsługiwanych pojazdów i przebyte trasy. Pracodawcy zwracają uwagę na brak punktów karnych i doświadczenie z ADR.',
    shouldContain: [
      'Kategorie prawa jazdy (B, C, C+E, D itp.)',
      'Karta kierowcy i zaświadczenie o niekaralności drogowej',
      'Rodzaj obsługiwanych pojazdów i ładunków',
      'Doświadczenie: krajowe/międzynarodowe, liczba km',
      'Znajomość tachografu cyfrowego i przepisów dotyczących czasu pracy',
    ],
    example: {
      name: 'Piotr Zając',
      position: 'Kierowca zawodowy kat. C+E',
      summary: 'Doświadczony kierowca z 10-letnim stażem w transporcie krajowym i międzynarodowym. Posiadam kat. C+E, kartę kierowcy i certyfikat ADR. Brak punktów karnych.',
      experience: [{
        position: 'Kierowca kat. C+E',
        company: 'Transport Nowak',
        dates: '2018 – obecnie',
        bullets: [
          'Obsługa tras krajowych i międzynarodowych (Niemcy, Holandia, Francja)',
          'Przewóz towarów ogólnych i materiałów niebezpiecznych (ADR klasa 3)',
          'Terminowa realizacja dostaw z bezbłędną dokumentacją CMR',
        ],
      }],
      skills: ['Kat. C+E', 'Karta kierowcy', 'ADR', 'Tachograf cyfrowy', 'CMR', 'GPS', 'Obsługa chłodni'],
    },
    tips: [
      'Zawsze podawaj aktualność prawa jazdy i karty kierowcy.',
      'Wspomnij o certyfikacie ADR, jeśli go posiadasz.',
      'Podaj liczbę przejechanych kilometrów lub obsługiwane kraje.',
      'Informacja o braku punktów karnych jest ważnym atutem.',
    ],
    faqs: [
      { q: 'Czy CV kierowcy musi mieć zdjęcie?', a: 'Nie jest wymagane, ale wielu pracodawców docenia profesjonalne zdjęcie w CV kierowcy zawodowego.' },
    ],
  },
  {
    slug: 'sprzedawca',
    icon: '🛍️',
    title: 'CV sprzedawcy',
    titleGen: 'CV sprzedawcy',
    intro: 'CV sprzedawcy powinno pokazać wyniki sprzedaży w liczbach i umiejętność pracy z klientem. Kluczowe są doświadczenie z kasą fiskalną, obsługa reklamacji i realizacja planów sprzedażowych.',
    shouldContain: [
      'Doświadczenie w obsłudze klienta i sprzedaży bezpośredniej',
      'Obsługa kasy fiskalnej i terminala płatniczego',
      'Znajomość obsługiwanych branż (AGD, RTV, odzież, spożywcze)',
      'Realizacja planów sprzedażowych',
      'Obsługa reklamacji i zwrotów',
    ],
    example: {
      name: 'Karolina Krawczyk',
      position: 'Sprzedawca / Doradca Klienta',
      summary: 'Sprzedawca z 4-letnim doświadczeniem w branży RTV/AGD. Regularnie przekraczam miesięczne plany sprzedażowe o 15–20% dzięki aktywnemu doradztwu i budowaniu relacji z klientami.',
      experience: [{
        position: 'Sprzedawca / Doradca Klienta',
        company: 'MediaExpert',
        dates: '2020 – obecnie',
        bullets: [
          'Obsługuję ok. 80 klientów dziennie w dziale RTV/AGD',
          'Regularnie przekraczam plan sprzedaży o 15–20%',
          'Wyróżniona dwukrotnie jako "Pracownik miesiąca" za wyniki sprzedażowe',
        ],
      }],
      skills: ['Obsługa klienta', 'Kasa fiskalna', 'Terminal płatniczy', 'Obsługa reklamacji', 'Cross-selling', 'POS'],
    },
    tips: [
      'Podawaj wyniki sprzedaży w procentach lub złotówkach.',
      'Wymień obsługiwane branże i typy produktów.',
      'Wspomnij o nagrodach i wyróżnieniach, jeśli je otrzymałeś.',
    ],
    faqs: [
      { q: 'Jak opisać doświadczenie sprzedawcy bez dużych sukcesów?', a: 'Skup się na zakresie obowiązków, liczbie obsługiwanych klientów i terminowości. Każde doświadczenie ma wartość.' },
    ],
  },
  {
    slug: 'nauczyciel',
    icon: '🎓',
    title: 'CV nauczyciela',
    titleGen: 'CV nauczyciela',
    intro: 'CV nauczyciela musi pokazać kwalifikacje pedagogiczne, nauczane przedmioty i doświadczenie z uczniami na różnych etapach edukacyjnych. Ważne są też dodatkowe umiejętności i zaangażowanie w życie szkoły.',
    shouldContain: [
      'Kwalifikacje pedagogiczne i dyplom ukończenia studiów',
      'Nauczane przedmioty i etapy edukacyjne',
      'Doświadczenie z uczniami o specjalnych potrzebach',
      'Znajomość podstawy programowej',
      'Dodatkowe aktywności: koła zainteresowań, wycieczki, projekty',
    ],
    example: {
      name: 'Magdalena Lewandowska',
      position: 'Nauczyciel języka angielskiego',
      summary: 'Nauczyciel z 8-letnim doświadczeniem w szkole podstawowej i liceum. Specjalizuję się w przygotowaniu do egzaminów zewnętrznych (matura, certyfikaty Cambridge). Pasjonat nowoczesnych metod nauczania.',
      experience: [{
        position: 'Nauczyciel języka angielskiego',
        company: 'Szkoła Podstawowa nr 12 w Warszawie',
        dates: '2016 – obecnie',
        bullets: [
          'Prowadzę zajęcia dla klas 4–8 (łącznie 180 uczniów)',
          'Przygotowuję uczniów do egzaminu ósmoklasisty — średni wynik moich uczniów: 82%',
          'Prowadzę koło teatralne i organizuję coroczny festiwal językowy',
        ],
      }],
      skills: ['Angielski C2', 'Metody aktywizujące', 'Tablice interaktywne', 'Google Classroom', 'Pedagogika specjalna', 'Podstawa programowa'],
    },
    tips: [
      'Wspomnij o wynikach egzaminów swoich uczniów, jeśli są dobre.',
      'Podkreśl zaangażowanie pozalekcyjne: koła, projekty, wyjazdy.',
      'Certyfikaty językowe (CELTA, TKT) są dużym atutem w CV nauczyciela angielskiego.',
    ],
    faqs: [
      { q: 'Czy CV nauczyciela bez stażu pracy ma szansę?', a: 'Tak — podkreśl praktyki pedagogiczne, wolontariat, korepetycje i własne projekty edukacyjne.' },
    ],
  },
  {
    slug: 'kucharz',
    icon: '🍳',
    title: 'CV kucharza',
    titleGen: 'CV kucharza',
    intro: 'CV kucharza powinno pokazać kuchnie i techniki kulinarne, w których się specjalizujesz, oraz doświadczenie w różnych typach lokali. Ważne są też certyfikaty sanitarne i umiejętność pracy pod presją czasu.',
    shouldContain: [
      'Specjalizacja kuchni (polska, włoska, azjatycka, fine dining)',
      'Techniki kulinarne i umiejętność planowania menu',
      'Doświadczenie w lokalach różnej kategorii',
      'Aktualne badania sanitarno-epidemiologiczne',
      'Praca pod presją, organizacja i zarządzanie zespołem kuchennym',
    ],
    example: {
      name: 'Tomasz Wiśniewski',
      position: 'Kucharz / Sous Chef',
      summary: 'Doświadczony kucharz z 6-letnim stażem w restauracjach średniego i wyższego segmentu. Specjalizuję się w kuchni polskiej i fusion. Lubię tworzyć sezonowe menu i pracować z lokalnymi produktami.',
      experience: [{
        position: 'Sous Chef',
        company: 'Restauracja „Smak Polski"',
        dates: '2020 – obecnie',
        bullets: [
          'Zarządzam kuchnią 5-osobowego zespołu przy 80 nakryciach dziennie',
          'Tworzę sezonowe menu w oparciu o lokalne produkty i trendy kulinarne',
          'Zredukowałem marnotrawstwo żywności o 20% przez optymalizację zamówień',
        ],
      }],
      skills: ['Kuchnia polska', 'Kuchnia fusion', 'HACCP', 'Zarządzanie kuchnią', 'Planowanie menu', 'Praca pod presją', 'Zamówienia surowców'],
    },
    tips: [
      'Podaj kuchnie, w których się specjalizujesz — to kluczowe dla pracodawcy.',
      'Wspomnij o certyfikatach sanitarnych i szkoleniach HACCP.',
      'Doświadczenie w fine dining lub restauracjach z gwiazdkami Michelin to duży atut.',
    ],
    faqs: [
      { q: 'Czy warto dołączyć zdjęcia potraw do CV kucharza?', a: 'CV powinno być tekstowe i czytelne dla ATS. Portfolio ze zdjęciami wyślij oddzielnie lub jako link.' },
    ],
  },
  {
    slug: 'fryzjer',
    icon: '💇',
    title: 'CV fryzjera',
    titleGen: 'CV fryzjera',
    intro: 'CV fryzjera powinno pokazać specjalizacje (koloryzacja, strzyżenie, stylizacja) i doświadczenie z różnymi typami włosów. Klientocentryczne podejście i budowanie stałej klienteli to klucz.',
    shouldContain: [
      'Specjalizacje: koloryzacja, strzyżenie, trwała ondulacja, stylizacja',
      'Znajomość technik (balayage, ombre, keratyna)',
      'Obsługiwane marki produktów',
      'Doświadczenie z różnymi typami włosów',
      'Liczba stałych klientów lub miesięczna rotacja',
    ],
    example: {
      name: 'Klaudia Mazur',
      position: 'Stylistka / Fryzjerka',
      summary: 'Fryzjerka z 5-letnim doświadczeniem, specjalizująca się w koloryzacji i technikach balayage. Posiadam stałą bazę 120 klientek i regularnie uczestniczę w szkoleniach Wella i L\'Oréal.',
      experience: [{
        position: 'Stylistka',
        company: 'Salon Beauty Studio',
        dates: '2019 – obecnie',
        bullets: [
          'Obsługuję ok. 30 klientek tygodniowo, specjalizuję się w koloryzacji i balayage',
          'Zbudowałam stałą bazę 120 lojalnych klientek',
          'Uczestniczyłam w pokazach i szkoleniach Wella Professionals (2021, 2023)',
        ],
      }],
      skills: ['Koloryzacja', 'Balayage', 'Ombre', 'Keratyna', 'Wella', 'L\'Oréal', 'Obsługa klienta', 'Stylizacja ślubna'],
    },
    tips: [
      'Podaj techniki koloryzacji — to najważniejszy element CV fryzjera.',
      'Wymień marki produktów, z którymi pracujesz.',
      'Certyfikaty ze szkoleń producentów (Wella, Schwarzkopf) zwiększają wiarygodność.',
    ],
    faqs: [
      { q: 'Czy CV fryzjera potrzebuje portfolio?', a: 'Tak — portfolio ze zdjęciami fryzur warto dołączyć jako link do Instagram lub osobny plik. Samo CV powinno być tekstowe.' },
    ],
  },
  {
    slug: 'logistyk',
    icon: '📦',
    title: 'CV logistyka',
    titleGen: 'CV logistyka',
    intro: 'CV logistyka powinno podkreślać doświadczenie z łańcuchem dostaw, systemami WMS i optymalizacją procesów. Kluczowe są umiejętności analityczne i znajomość procedur celnych przy transporcie międzynarodowym.',
    shouldContain: [
      'Systemy WMS i ERP (SAP, Oracle, Comarch)',
      'Zarządzanie łańcuchem dostaw i magazynem',
      'Transport krajowy i międzynarodowy',
      'Procedury celne i dokumentacja (CMR, AWB, B/L)',
      'Optymalizacja kosztów i procesów logistycznych',
    ],
    example: {
      name: 'Bartosz Kowalczyk',
      position: 'Specjalista ds. Logistyki',
      summary: 'Logistyk z 5-letnim doświadczeniem w zarządzaniu magazynem i łańcuchem dostaw. Specjalizuję się w optymalizacji procesów i wdrożeniu systemów WMS, co pozwoliło mi obniżyć koszty operacyjne o 18%.',
      experience: [{
        position: 'Specjalista ds. Logistyki',
        company: 'Firma Dystrybucyjna ABC',
        dates: '2020 – obecnie',
        bullets: [
          'Zarządzam przepływem 500+ SKU w magazynie 3000 m²',
          'Wdrożyłem system WMS (SAP EWM), skracając czas kompletacji zamówień o 25%',
          'Koordynuję dostawy z 12 dostawcami krajowymi i zagranicznymi',
        ],
      }],
      skills: ['SAP EWM', 'WMS', 'Incoterms', 'CMR', 'MS Excel', 'Power BI', 'Zarządzanie magazynem', 'Import/Eksport'],
    },
    tips: [
      'Wymień systemy WMS/ERP, z których korzystasz.',
      'Podaj wymierne efekty optymalizacji (czas, koszty, liczba SKU).',
      'Znajomość Incoterms i dokumentów celnych to ważny atut.',
    ],
    faqs: [
      { q: 'Jakie certyfikaty zwiększają wartość CV logistyka?', a: 'Certyfikat APICS CSCP, szkolenia z SAP lub CIPS wyraźnie wyróżniają kandydata w branży logistycznej.' },
    ],
  },
  {
    slug: 'specjalista-hr',
    icon: '👥',
    title: 'CV specjalisty HR',
    titleGen: 'CV specjalisty HR',
    intro: 'CV specjalisty HR powinno pokazać doświadczenie w rekrutacji, znajomość prawa pracy i systemy HRMS. Ważne są umiejętności miękkie, np. komunikacja i mediacja.',
    shouldContain: [
      'Procesy rekrutacyjne end-to-end',
      'Systemy ATS i HRMS (SAP HR, Workday, Enova)',
      'Znajomość prawa pracy (KP, ZUS, PPK)',
      'Onboarding, offboarding i administracja kadrowo-płacowa',
      'Employer branding i komunikacja wewnętrzna',
    ],
    example: {
      name: 'Agnieszka Pawlak',
      position: 'HR Business Partner',
      summary: 'HR-owiec z 6-letnim doświadczeniem w rekrutacji i zarządzaniu talentami. Przeprowadziłam ponad 500 procesów rekrutacyjnych dla klientów z branż IT, finansowej i produkcyjnej.',
      experience: [{
        position: 'HR Business Partner',
        company: 'Korporacja XYZ',
        dates: '2019 – obecnie',
        bullets: [
          'Realizuję 80–100 procesów rekrutacyjnych rocznie dla działów IT i Finance',
          'Wdrożyłam ATS (Workday Recruiting), skracając czas rekrutacji o 30%',
          'Koordynuję programy onboardingowe dla 50+ nowych pracowników rocznie',
        ],
      }],
      skills: ['Rekrutacja', 'Prawo pracy', 'Workday', 'SAP HR', 'Employer Branding', 'Assessment Center', 'Mediacja', 'KPI HR'],
    },
    tips: [
      'Podaj liczbę przeprowadzonych rekrutacji — to mierzalny wynik.',
      'Wymień systemy ATS i HRMS, z których korzystasz.',
      'Znajomość prawa pracy i KP jest podstawą w każdym CV HR.',
    ],
    faqs: [
      { q: 'Czy certyfikat SHRM lub CIPD warto umieścić w CV?', a: 'Zdecydowanie tak — to prestiżowe certyfikaty rozpoznawalne przez pracodawców na całym świecie.' },
    ],
  },
  {
    slug: 'magazynier',
    icon: '🏷️',
    title: 'CV magazyniera',
    titleGen: 'CV magazyniera',
    intro: 'CV magazyniera powinno jasno pokazać obsługiwane systemy magazynowe, uprawnienia na wózek widłowy i doświadczenie z inwentaryzacją. Liczy się dokładność i fizyczna sprawność.',
    shouldContain: [
      'Uprawnienia UDT na wózek widłowy (jeśli posiadasz)',
      'Obsługa systemów WMS i skanerów magazynowych',
      'Przyjmowanie, wydawanie i inwentaryzacja towarów',
      'Znajomość procedur FIFO/FEFO',
      'Obsługa dokumentacji magazynowej',
    ],
    example: {
      name: 'Krzysztof Dąbrowski',
      position: 'Magazynier / Operator wózka widłowego',
      summary: 'Magazynier z 4-letnim doświadczeniem w magazynach wysokiego składowania. Posiadam uprawnienia UDT na wózek widłowy kat. II WJO. Dbam o porządek i terminową realizację wydań.',
      experience: [{
        position: 'Magazynier',
        company: 'Centrum Logistyczne DEF',
        dates: '2021 – obecnie',
        bullets: [
          'Obsługuję przyjęcia i wydania ok. 200 palet dziennie',
          'Prowadzę inwentaryzacje kwartalne z dokładnością 99,8%',
          'Obsługuję wózki widłowe czołowe i reach truck w magazynie 15 000 m²',
        ],
      }],
      skills: ['Wózek widłowy UDT', 'WMS', 'Skaner magazynowy', 'FIFO', 'Inwentaryzacja', 'Obsługa dokumentacji', 'Reach truck'],
    },
    tips: [
      'Zawsze podawaj numer i kategorie uprawnień UDT.',
      'Wspomnij o powierzchni obsługiwanego magazynu i liczbie SKU.',
      'Dokładność w inwentaryzacji to kluczowy atut.',
    ],
    faqs: [
      { q: 'Czy bez UDT można dostać pracę jako magazynier?', a: 'Tak — wiele firm zatrudnia magazynierów bez UDT i umożliwia zdobycie uprawnień w trakcie pracy.' },
    ],
  },
  {
    slug: 'kelner',
    icon: '🍽️',
    title: 'CV kelnera',
    titleGen: 'CV kelnera',
    intro: 'CV kelnera powinno podkreślać obsługę klienta, znajomość win lub menu degustacyjnego i doświadczenie w lokalach różnych kategorii. Ważna jest szybkość, precyzja i wysoka kultura osobista.',
    shouldContain: [
      'Doświadczenie w lokalach (restauracja, hotel, catering)',
      'Obsługa systemu POS i terminala płatniczego',
      'Znajomość menu, kart win i napojów',
      'Obsługa klientów w różnych językach (jeśli dotyczy)',
      'Praca pod presją w godzinach szczytu',
    ],
    example: {
      name: 'Natalia Woźniak',
      position: 'Kelnerka / Hostessa',
      summary: 'Doświadczona kelnerka z 4 latami pracy w restauracjach hotelowych i à la carte. Specjalizuję się w obsłudze bankietów i eventów korporacyjnych. Biegle mówię po angielsku i po rosyjsku.',
      experience: [{
        position: 'Kelnerka',
        company: 'Hotel Marriott Warszawa',
        dates: '2021 – obecnie',
        bullets: [
          'Obsługuję restaurację hotelową (160 miejsc) i bankiety do 300 osób',
          'Specjalizuję się w serwisie à la carte i cateringach korporacyjnych',
          'Uzyskałam najwyższe oceny gości w kwartalnych ankietach satysfakcji (4,8/5)',
        ],
      }],
      skills: ['Obsługa à la carte', 'Serwis bankietowy', 'POS', 'Karta win', 'Angielski B2', 'Rosyjski B1', 'Obsługa klienta'],
    },
    tips: [
      'Podaj rodzaje lokali i liczbę obsługiwanych miejsc.',
      'Znajomość języków obcych jest dużym plusem w hotelach i restauracjach turystycznych.',
      'Certyfikat sommeliera lub szkolenie barmańskie wyróżnią Twoje CV.',
    ],
    faqs: [
      { q: 'Czy CV kelnera bez doświadczenia ma szansę?', a: 'Tak — podkreśl komunikatywność, gotowość do nauki, doświadczenie w obsłudze klienta (np. sprzedaż) i dyspozycyjność.' },
    ],
  },
  {
    slug: 'elektryk',
    icon: '⚡',
    title: 'CV elektryka',
    titleGen: 'CV elektryka',
    intro: 'CV elektryka musi pokazać uprawnienia SEP, rodzaj instalacji, przy których pracujesz i doświadczenie z projektami komercyjnymi lub przemysłowymi. Liczy się precyzja i znajomość norm.',
    shouldContain: [
      'Uprawnienia SEP (G1, E, D) z grupą napięciową',
      'Instalacje: domowe, przemysłowe, fotowoltaika, BMS',
      'Znajomość norm IEC i przepisów bezpieczeństwa',
      'Obsługa pomiarów i czytanie schematów elektrycznych',
      'Doświadczenie z projektami inwestycyjnymi',
    ],
    example: {
      name: 'Michał Adamski',
      position: 'Elektryk instalacyjny',
      summary: 'Elektryk z 7-letnim doświadczeniem w instalacjach elektrycznych w budownictwie mieszkaniowym i komercyjnym. Posiadam uprawnienia SEP do 1 kV (E i D). Specjalizuję się w instalacjach fotowoltaicznych.',
      experience: [{
        position: 'Elektryk instalacyjny',
        company: 'Firma Budowlana GHI',
        dates: '2018 – obecnie',
        bullets: [
          'Wykonuję instalacje elektryczne w nowych budynkach mieszkalnych (200+ lokali rocznie)',
          'Instaluję systemy fotowoltaiczne o mocy do 50 kWp',
          'Prowadzę pomiary i odbiory instalacji zgodnie z normą PN-HD 60364',
        ],
      }],
      skills: ['SEP do 1 kV', 'Fotowoltaika', 'Instalacje LV/MV', 'Pomiary', 'Czytanie schematów', 'BMS', 'PN-HD 60364'],
    },
    tips: [
      'Zawsze podawaj grupę napięciową i zakres uprawnień SEP.',
      'Specjalizacja w fotowoltaice lub automatyce budynkowej jest bardzo poszukiwana.',
      'Wymień normy i przepisy, zgodnie z którymi pracujesz.',
    ],
    faqs: [
      { q: 'Czy elektryk bez uprawnień SEP znajdzie pracę?', a: 'Można pracować jako pomocnik elektryka, jednak uprawnienia SEP są niezbędne do samodzielnego wykonywania i odbioru instalacji.' },
    ],
  },
  {
    slug: 'recepcjonistka',
    icon: '🛎️',
    title: 'CV recepcjonistki',
    titleGen: 'CV recepcjonistki',
    intro: 'CV recepcjonistki powinno podkreślać znajomość języków obcych, obsługę systemów hotelowych i umiejętności komunikacyjne. Pierwsze wrażenie zaczyna się już od CV.',
    shouldContain: [
      'Obsługa systemów: Opera, Fidelio, Hotix lub podobnych',
      'Znajomość języków obcych (angielski obowiązkowy)',
      'Check-in / check-out i obsługa rezerwacji',
      'Windykacja należności i obsługa kasy',
      'Protokoły obsługi gościa i standary hotelowe',
    ],
    example: {
      name: 'Ewa Grabowska',
      position: 'Recepcjonistka hotelowa',
      summary: 'Recepcjonistka z 3-letnim doświadczeniem w 4-gwiazdkowym hotelu. Biegle posługuję się angielskim i niemieckim. Specjalizuję się w obsłudze gości korporacyjnych i organizacji eventów.',
      experience: [{
        position: 'Recepcjonistka',
        company: 'Hotel Hilton Wrocław',
        dates: '2022 – obecnie',
        bullets: [
          'Obsługuję recepcję w hotelu 250 pokoi (4 gwiazdki)',
          'Przeprowadzam check-in/out, rezerwacje i płatności w systemie Opera PMS',
          'Uzyskuję regularnie oceny 5/5 w ankietach satysfakcji gości',
        ],
      }],
      skills: ['Opera PMS', 'Angielski C1', 'Niemiecki B2', 'Obsługa klienta', 'Check-in/out', 'Rezerwacje', 'Windykacja'],
    },
    tips: [
      'Zawsze podawaj poziomy znajomości języków obcych.',
      'System rezerwacyjny (Opera, Fidelio) to obowiązkowy punkt w CV.',
      'Oceny gości i nagrody w ankietach satysfakcji to mocne argumenty.',
    ],
    faqs: [
      { q: 'Czy recepcjonistka hotelowa musi znać angielski?', a: 'Tak — angielski jest standardem. W hotelach sieciowych często wymagany jest poziom minimum B2/C1.' },
    ],
  },
  {
    slug: 'opiekunka-osob-starszych',
    icon: '🤝',
    title: 'CV opiekunki osób starszych',
    titleGen: 'CV opiekunki osób starszych',
    intro: 'CV opiekunki osób starszych powinno pokazać doświadczenie z podopiecznymi, posiadane certyfikaty i umiejętności pielęgnacyjne. Empatia i cierpliwość są równie ważne jak kwalifikacje.',
    shouldContain: [
      'Kwalifikacje: kurs opiekuna, certyfikat pierwszej pomocy',
      'Doświadczenie z podopiecznymi (w domu, DPS, za granicą)',
      'Zakres opieki: pielęgnacja, rehabilitacja, codzienne czynności',
      'Obsługiwane schorzenia (demencja, Parkinson, niepełnosprawność)',
      'Znajomość języka (w przypadku pracy za granicą)',
    ],
    example: {
      name: 'Halina Kowalska',
      position: 'Opiekunka osób starszych',
      summary: 'Opiekunka z 5-letnim doświadczeniem, w tym 2 lata pracy w Niemczech. Posiadam certyfikat opiekuna i kurs pierwszej pomocy. Specjalizuję się w opiece nad osobami z demencją.',
      experience: [{
        position: 'Opiekunka',
        company: 'Prywatna rodzina, Niemcy',
        dates: '2022 – 2024',
        bullets: [
          'Sprawowałam całodobową opiekę nad 82-letnią podopieczną z demencją',
          'Prowadziłam dokumentację opiekuńczą i kontakt z rodziną',
          'Pomagałam przy rehabilitacji i ćwiczeniach pamięciowych',
        ],
      }],
      skills: ['Opieka nad starszymi', 'Demencja', 'Pierwsza pomoc', 'Pielęgnacja', 'Język niemiecki B1', 'Rehabilitacja', 'Dokumentacja'],
    },
    tips: [
      'Certyfikaty i kursy opiekuńcze znacznie zwiększają wartość CV.',
      'Wymień schorzenia, z którymi masz doświadczenie.',
      'Referencje od poprzednich rodzin są bardzo cenione przez pracodawców.',
    ],
    faqs: [
      { q: 'Czy opiekunka bez certyfikatu znajdzie pracę?', a: 'Tak, szczególnie w opiece domowej. Jednak certyfikat opiekuna osoby starszej znacznie zwiększa szanse i wynagrodzenie.' },
    ],
  },
  {
    slug: 'mechanik-samochodowy',
    icon: '🔧',
    title: 'CV mechanika samochodowego',
    titleGen: 'CV mechanika samochodowego',
    intro: 'CV mechanika samochodowego powinno pokazać specjalizację (silnik, elektryka, blacharnia) i obsługiwane marki pojazdów. Certyfikaty producentów i znajomość diagnostyki komputerowej to duże atuty.',
    shouldContain: [
      'Specjalizacja: silnik, skrzynia biegów, elektryka, blacharnia',
      'Obsługiwane marki (np. BMW, VW, Toyota)',
      'Certyfikaty autoryzowane (jeśli posiadasz)',
      'Obsługa diagnostyki komputerowej (OBD, VCDS, ISTA)',
      'Prawo jazdy kat. B',
    ],
    example: {
      name: 'Damian Szymański',
      position: 'Mechanik samochodowy',
      summary: 'Mechanik z 8-letnim doświadczeniem w serwisach autoryzowanych i niezależnych. Specjalizuję się w silnikach spalinowych i diagnostyce komputerowej. Certyfikowany przez Bosch Car Service.',
      experience: [{
        position: 'Mechanik samochodowy',
        company: 'Autoryzowany Serwis BMW',
        dates: '2019 – obecnie',
        bullets: [
          'Wykonuję naprawy silnika, zawieszenia i układu hamulcowego w samochodach BMW i MINI',
          'Przeprowadzam diagnostykę komputerową za pomocą systemu ISTA+',
          'Obsługuję 5–7 pojazdów dziennie z zachowaniem terminowości',
        ],
      }],
      skills: ['Diagnostyka OBD', 'ISTA+', 'VCDS', 'Silniki benzynowe/diesel', 'Zawieszenie', 'Elektryka', 'Bosch Car Service'],
    },
    tips: [
      'Podaj obsługiwane marki — serwisy autoryzowane szukają mechaników z doświadczeniem danej marki.',
      'Certyfikaty producentów (Bosch, Continental) to duże wyróżnienie.',
      'Znajomość oprogramowania diagnostycznego jest obowiązkowa.',
    ],
    faqs: [
      { q: 'Czy mechanik bez certyfikatów znajdzie pracę w ASO?', a: 'Certyfikaty producenta ułatwiają, ale nie są zawsze wymagane. Doświadczenie w danej marce lub technikum motoryzacyjne też przekonują pracodawcę.' },
    ],
  },
  {
    slug: 'pielegniarka',
    icon: '🩺',
    title: 'CV pielęgniarki',
    titleGen: 'CV pielęgniarki',
    intro: 'CV pielęgniarki musi jasno pokazać specjalizację, posiadane uprawnienia i doświadczenie z pacjentami różnych oddziałów. Licencja i aktualny wpis do Okręgowej Izby Pielęgniarek są obowiązkowe.',
    shouldContain: [
      'Numer prawa wykonywania zawodu',
      'Specjalizacja lub kurs kwalifikacyjny',
      'Oddziały i specjalności (chirurgia, SOR, POZ, onkologia)',
      'Umiejętności: wkłucia, leki, dokumentacja medyczna',
      'Kursy z pierwszej pomocy i kwalifikowanej pierwszej pomocy',
    ],
    example: {
      name: 'Joanna Wierzbicka',
      position: 'Pielęgniarka specjalistka — chirurgia',
      summary: 'Pielęgniarka z 9-letnim doświadczeniem na oddziałach chirurgicznych. Posiadam specjalizację z pielęgniarstwa chirurgicznego i certyfikat z opieki perioperacyjnej.',
      experience: [{
        position: 'Pielęgniarka oddziałowa',
        company: 'Szpital Kliniczny, Oddział Chirurgii Ogólnej',
        dates: '2016 – obecnie',
        bullets: [
          'Sprawuję opiekę pielęgniarską nad pacjentami przed i po zabiegach chirurgicznych',
          'Prowadzę dokumentację medyczną (e-zdrowie) i raportowanie dyżurów',
          'Mentoring dla studentów i stażystów na oddziale (3 osoby)',
        ],
      }],
      skills: ['Chirurgia', 'Dokumentacja medyczna', 'Opieka perioperacyjna', 'Wkłucia', 'E-zdrowie', 'EKG', 'KPP'],
    },
    tips: [
      'Numer prawa wykonywania zawodu jest obowiązkowy w CV pielęgniarki.',
      'Specjalizacja lub kurs kwalifikacyjny znacznie podnosi wartość CV.',
      'Doświadczenie na SOR lub OIOM jest bardzo cenione.',
    ],
    faqs: [
      { q: 'Czy pielęgniarka po studiach bez doświadczenia ma szanse?', a: 'Tak — podkreśl praktyki kliniczne, staże i predyspozycje do pracy w konkretnej specjalności.' },
    ],
  },
  {
    slug: 'grafik',
    icon: '🎨',
    title: 'CV grafika',
    titleGen: 'CV grafika',
    intro: 'CV grafika musi zawierać link do portfolio — to ważniejsze niż jakikolwiek certyfikat. Podkreśl oprogramowanie i specjalizację (UI/UX, branding, ilustracja, motion).',
    shouldContain: [
      'Link do portfolio (Behance, Dribbble, własna strona)',
      'Oprogramowanie: Adobe CC, Figma, Sketch, Canva',
      'Specjalizacja: UI/UX, identyfikacja wizualna, ilustracja, motion',
      'Doświadczenie komercyjne: klienci, kampanie, projekty',
      'Zrozumienie procesu designu i briefowania',
    ],
    example: {
      name: 'Zuzanna Karpowicz',
      position: 'Graphic Designer / UI Designer',
      summary: 'Graficzka z 5-letnim doświadczeniem w projektowaniu identyfikacji wizualnej i interfejsów. Specjalizuję się w UI/UX i pracy w środowiskach Agile. Portfolio: zuza.design',
      experience: [{
        position: 'Senior Graphic Designer',
        company: 'Agencja Kreatywna Studio K',
        dates: '2020 – obecnie',
        bullets: [
          'Projektuję identyfikację wizualną dla startupów i firm MŚP (30+ projektów)',
          'Tworzę interfejsy mobilne i webowe w Figma (10+ wdrożonych produktów)',
          'Prowadzę warsztaty designu i prezentacje klientom',
        ],
      }],
      skills: ['Figma', 'Adobe Illustrator', 'Photoshop', 'After Effects', 'Canva', 'UI/UX', 'Branding', 'Motion Design'],
    },
    tips: [
      'Portfolio to Twoja najlepsza wizytówka — link musi działać i być aktualny.',
      'Opisuj projekty przez efekty i zakres, nie tylko nazwę klienta.',
      'Wymień oprogramowanie, z którym rzeczywiście pracujesz na co dzień.',
    ],
    faqs: [
      { q: 'Czy grafik potrzebuje dyplomu?', a: 'Dyplom jest pomocny, ale portfolio i doświadczenie mówią więcej. Wiele świetnych grafików jest self-taught.' },
    ],
  },
  {
    slug: 'operator-wozka-widlowego',
    icon: '🚜',
    title: 'CV operatora wózka widłowego',
    titleGen: 'CV operatora wózka widłowego',
    intro: 'CV operatora wózka widłowego musi jasno pokazać posiadane uprawnienia UDT i rodzaje obsługiwanych wózków. Doświadczenie w magazynach wysokiego składowania to duży plus.',
    shouldContain: [
      'Uprawnienia UDT (numer, kategoria, ważność)',
      'Rodzaje wózków: czołowe, reach truck, order picker, wózki boczne',
      'Doświadczenie w magazynach: powierzchnia, liczba palet',
      'Obsługa systemu WMS i skanerów',
      'Znajomość procedur BHP i bezpieczeństwa magazynowego',
    ],
    example: {
      name: 'Rafał Kubiak',
      position: 'Operator wózka widłowego',
      summary: 'Operator z 6-letnim doświadczeniem w magazynach wysokiego składowania. Posiadam uprawnienia UDT na wózki czołowe i reach truck (ważne do 2028). Dbam o bezpieczeństwo i terminowość wydań.',
      experience: [{
        position: 'Operator wózka widłowego',
        company: 'Centrum Logistyczne JKL',
        dates: '2019 – obecnie',
        bullets: [
          'Obsługuję wózki czołowe i reach truck w magazynie wysokiego składowania (20 m)',
          'Realizuję 150+ operacji paletowych dziennie z dokładnością 99,5%',
          'Prowadzę codzienne przeglądy wózka i dokumentację BHP',
        ],
      }],
      skills: ['Wózek czołowy UDT', 'Reach truck UDT', 'Order picker', 'WMS', 'BHP', 'Inwentaryzacja', 'Skaner magazynowy'],
    },
    tips: [
      'Podaj numer uprawnień UDT i datę ważności.',
      'Wymień wszystkie kategorie wózków, które obsługujesz.',
      'Brak wypadków i dobry rekord BHP to ważny atut.',
    ],
    faqs: [
      { q: 'Jak długo trwa zdobycie uprawnień UDT na wózek widłowy?', a: 'Kurs trwa zazwyczaj 3–5 dni i kończy się egzaminem przed komisją UDT. Uprawnienia są ważne 5 lat.' },
    ],
  },
  {
    slug: 'przedstawiciel-handlowy',
    icon: '🤝',
    title: 'CV przedstawiciela handlowego',
    titleGen: 'CV przedstawiciela handlowego',
    intro: 'CV przedstawiciela handlowego musi pokazać wyniki sprzedaży liczbami, obsługiwany region i portfolio klientów. Kluczowe są realizacja targetów i doświadczenie z procesem sprzedaży B2B lub B2C.',
    shouldContain: [
      'Wyniki: realizacja planu sprzedaży (% targetu)',
      'Obsługiwany region i liczba klientów',
      'Branże i produkty/usługi, które sprzedawałeś',
      'Systemy CRM (Salesforce, HubSpot, Pipedrive)',
      'Prawo jazdy kat. B i doświadczenie w terenie',
    ],
    example: {
      name: 'Robert Jaworski',
      position: 'Regionalny Przedstawiciel Handlowy',
      summary: 'Przedstawiciel handlowy z 6-letnim doświadczeniem w sprzedaży B2B rozwiązań IT. Regularnie realizuję 120% planu sprzedaży i zarządzam portfolio 80 klientów korporacyjnych.',
      experience: [{
        position: 'Regionalny Przedstawiciel Handlowy',
        company: 'Firma IT Solutions',
        dates: '2018 – obecnie',
        bullets: [
          'Zarządzam portfelem 80 klientów B2B w woj. mazowieckim i łódzkim',
          'Regularnie realizuję 115–125% planu sprzedażowego',
          'Pozyskałem 12 nowych klientów korporacyjnych o łącznym kontrakcie 1,2 mln PLN rocznie',
        ],
      }],
      skills: ['Sprzedaż B2B', 'CRM Salesforce', 'Negocjacje', 'Cold calling', 'Account management', 'Prawa jazdy kat. B', 'Raportowanie'],
    },
    tips: [
      'Podaj procent realizacji targetów — to najważniejszy wskaźnik.',
      'Wymień obsługiwane systemy CRM.',
      'Liczba i wartość pozyskanych klientów to mocne argumenty.',
    ],
    faqs: [
      { q: 'Czy CV handlowca musi mieć list motywacyjny?', a: 'Nie jest wymagany, ale dobrze napisany list motywacyjny może wyróżnić Cię spośród kandydatów z podobnymi wynikami.' },
    ],
  },
  {
    slug: 'kasjer',
    icon: '🛒',
    title: 'CV kasjera',
    titleGen: 'CV kasjera',
    intro: 'CV kasjera powinno podkreślać szybkość i dokładność obsługi klientów, doświadczenie z kasą fiskalną i umiejętność pracy w zatłoczonych środowiskach.',
    shouldContain: [
      'Obsługa kasy fiskalnej i terminala płatniczego',
      'Przyjmowanie i wydawanie reszty bez błędów',
      'Obsługa programów lojalnościowych',
      'Praca w godzinach szczytu i pod presją czasu',
      'Obsługa reklamacji przy kasie',
    ],
    example: {
      name: 'Sylwia Piotrowska',
      position: 'Kasjerka / Pracownik obsługi klienta',
      summary: 'Kasjerka z 3-letnim doświadczeniem w handlu detalicznym. Sprawnie obsługuję kasę fiskalną i terminal płatniczy, dbam o krótki czas oczekiwania klientów i bezbłędne rozliczenia.',
      experience: [{
        position: 'Kasjerka',
        company: 'Biedronka — oddział Warszawa Wola',
        dates: '2022 – obecnie',
        bullets: [
          'Obsługuję 200–300 klientów dziennie na stanowisku kasowym',
          'Zamykam kasę z zerową różnicą w 98% zmian',
          'Pomagam klientom w obsłudze kart lojalnościowych i reklamacjach',
        ],
      }],
      skills: ['Kasa fiskalna', 'Terminal płatniczy', 'Obsługa klienta', 'Przyjmowanie dostaw', 'Program lojalnościowy', 'Praca zmianowa'],
    },
    tips: [
      'Podkreśl bezbłędność rozliczeń i szybkość obsługi.',
      'Gotowość do pracy w weekendy i święta jest ceniona w handlu.',
    ],
    faqs: [
      { q: 'Czy kasjer bez doświadczenia dostanie pracę?', a: 'Tak — wiele sieci handlowych przyjmuje kandydatów bez doświadczenia i szkoli ich wewnętrznie.' },
    ],
  },
  {
    slug: 'pracownik-produkcji',
    icon: '🏭',
    title: 'CV pracownika produkcji',
    titleGen: 'CV pracownika produkcji',
    intro: 'CV pracownika produkcji powinno pokazać obsługiwane maszyny, znajomość norm jakości i doświadczenie z pracą zmianową. Ważne jest też doświadczenie z procedurami BHP.',
    shouldContain: [
      'Obsługiwane maszyny i linie produkcyjne',
      'Standardy jakości: ISO, HACCP, GMP',
      'Praca zmianowa i fizyczna gotowość',
      'Procedury BHP i doświadczenie z audytami',
      'Kontrola jakości i dokumentacja produkcyjna',
    ],
    example: {
      name: 'Marcin Kowalczyk',
      position: 'Operator maszyn produkcyjnych',
      summary: 'Pracownik produkcji z 4-letnim doświadczeniem w branży spożywczej. Obsługuję linie pakujące i maszyny dozujące. Praca w systemie 3-zmianowym, znajomość norm HACCP i GMP.',
      experience: [{
        position: 'Operator linii produkcyjnej',
        company: 'Zakład Produkcji Spożywczej MNO',
        dates: '2021 – obecnie',
        bullets: [
          'Obsługuję linię pakującą o wydajności 1200 szt./godz.',
          'Przeprowadzam kontrolę jakości i odrzucam braki zgodnie z normą ISO 9001',
          'Uczestniczyłem w 3 wewnętrznych audytach jakości bez uwag',
        ],
      }],
      skills: ['Linia produkcyjna', 'HACCP', 'GMP', 'ISO 9001', 'Kontrola jakości', 'Praca zmianowa', 'BHP', '5S'],
    },
    tips: [
      'Wymień konkretne maszyny lub linie, które obsługujesz.',
      'Certyfikaty BHP i szkolenia z norm jakości są dużym plusem.',
      'Doświadczenie z systemem 5S lub Lean jest cenione w fabrykach.',
    ],
    faqs: [
      { q: 'Czy pracownik produkcji bez doświadczenia może liczyć na zatrudnienie?', a: 'Tak — wiele zakładów przyjmuje kandydatów bez doświadczenia i szkoli ich na stanowisku. Ważna jest gotowość do pracy zmianowej.' },
    ],
  },
  {
    slug: 'pracownik-ochrony',
    icon: '🛡️',
    title: 'CV pracownika ochrony',
    titleGen: 'CV pracownika ochrony',
    intro: 'CV pracownika ochrony musi jasno pokazać licencję SUFO (jeśli dotyczy), doświadczenie z obiektami i obszarami obsługi oraz przebyte szkolenia.',
    shouldContain: [
      'Licencja pracownika ochrony I lub II stopnia (jeśli posiadasz)',
      'Rodzaje ochranianego mienia (obiekty, wydarzenia, sklepy)',
      'Obsługa systemów alarmowych i monitoringu CCTV',
      'Kurs pierwszej pomocy',
      'Prawo jazdy kat. B (jeśli wymagane)',
    ],
    example: {
      name: 'Grzegorz Nowicki',
      position: 'Pracownik ochrony',
      summary: 'Pracownik ochrony z 5-letnim doświadczeniem. Posiadam licencję SUFO I stopnia i certyfikat pierwszej pomocy. Doświadczenie w ochronie obiektów komercyjnych i eventów masowych.',
      experience: [{
        position: 'Pracownik ochrony',
        company: 'Agencja Ochrony Bezpieczny Dom',
        dates: '2020 – obecnie',
        bullets: [
          'Ochraniałem centrum handlowe (45 000 m² pow. użytkowej)',
          'Obsługuję system monitoringu CCTV i kontroli dostępu',
          'Uczestniczyłem w zabezpieczeniu 20+ eventów masowych (do 5 000 osób)',
        ],
      }],
      skills: ['Licencja SUFO I stopnia', 'Monitoring CCTV', 'Kontrola dostępu', 'Pierwsza pomoc', 'Prawo jazdy B', 'Radiotelefonista', 'Eventy masowe'],
    },
    tips: [
      'Podaj numer i stopień licencji pracownika ochrony.',
      'Doświadczenie na eventach masowych jest dużym wyróżnikiem.',
      'Certyfikat ratownictwa medycznego lub KPP zwiększa wartość CV.',
    ],
    faqs: [
      { q: 'Czy pracownik ochrony bez licencji SUFO znajdzie pracę?', a: 'Tak — część pracodawców zatrudnia bez licencji (np. sklepy), ale licencja znacznie poszerza możliwości i wynagrodzenie.' },
    ],
  },
  {
    slug: 'spawacz',
    icon: '🔥',
    title: 'CV spawacza',
    titleGen: 'CV spawacza',
    intro: 'CV spawacza musi pokazać posiadane uprawnienia spawalnicze (metody, materiały) i doświadczenie z różnymi typami złączy. Branże przemysłowe i budowlane szukają konkretnych kwalifikacji.',
    shouldContain: [
      'Metody spawania: MIG/MAG (135/138), TIG (141), elektroda (111)',
      'Materiały: stal, stal nierdzewna, aluminium',
      'Certyfikaty wg PN-EN ISO 9606',
      'Spawanie konstrukcji, rurociągów lub zbiorników',
      'Kontrola jakości i badania złączy',
    ],
    example: {
      name: 'Łukasz Baran',
      position: 'Spawacz MIG/MAG, TIG',
      summary: 'Spawacz z 8-letnim doświadczeniem w spawaniu konstrukcji stalowych i rurociągów. Posiadam certyfikaty PN-EN ISO 9606-1 (metody 135 i 141). Doświadczenie z pracą na budowach przemysłowych w Polsce i Niemczech.',
      experience: [{
        position: 'Spawacz',
        company: 'Konstruktor Stal Sp. z o.o.',
        dates: '2017 – obecnie',
        bullets: [
          'Spawam konstrukcje stalowe metodami MIG/MAG i TIG',
          'Realizuję spawy ciśnieniowe rurociągów zgodnie z normą PN-EN 13480',
          'Przeszedłem 4 recertyfikacje uprawnień spawalniczych bez zastrzeżeń',
        ],
      }],
      skills: ['MIG/MAG (135)', 'TIG (141)', 'Elektroda (111)', 'Stal nierdzewna', 'ISO 9606', 'Spawanie rurociągów', 'Kontrola jakości'],
    },
    tips: [
      'Podaj metody spawania z kodami (135, 141 itd.) — to standard branżowy.',
      'Certyfikaty PN-EN ISO 9606 są sprawdzane przez pracodawcę.',
      'Doświadczenie ze stalą nierdzewną lub aluminium jest bardzo cenione.',
    ],
    faqs: [
      { q: 'Czy spawacz bez certyfikatów znajdzie pracę?', a: 'W prostych pracach instalacyjnych tak, ale do pracy przy konstrukcjach ciśnieniowych certyfikaty są obowiązkowe.' },
    ],
  },
  {
    slug: 'doradca-klienta',
    icon: '💬',
    title: 'CV doradcy klienta',
    titleGen: 'CV doradcy klienta',
    intro: 'CV doradcy klienta powinno pokazać umiejętności komunikacyjne, efektywność obsługi i ewentualne doświadczenie call center. Kluczowe są wskaźniki satysfakcji klienta (CSAT, NPS).',
    shouldContain: [
      'Kanały obsługi: telefon, chat, e-mail, spotkania',
      'Obsługiwane systemy CRM i ticketingowe',
      'Wskaźniki: CSAT, NPS, czas rozwiązania zgłoszenia',
      'Obsługa reklamacji i eskalacja',
      'Języki obsługi (jeśli wielojęzyczna)',
    ],
    example: {
      name: 'Patrycja Kaczmarek',
      position: 'Doradca Klienta / Specjalista BOK',
      summary: 'Specjalistka BOK z 4-letnim doświadczeniem w obsłudze klienta B2C i B2B. Utrzymuję CSAT 92% i średni czas pierwszej odpowiedzi poniżej 2 minut.',
      experience: [{
        position: 'Doradca Klienta',
        company: 'Firma Telekomunikacyjna XYZ',
        dates: '2021 – obecnie',
        bullets: [
          'Obsługuję 60–80 kontaktów dziennie (telefon, chat, e-mail)',
          'Utrzymuję wskaźnik CSAT 92% i NPS 45',
          'Rozwiązuję reklamacje pierwszego kontaktu w 85% przypadków',
        ],
      }],
      skills: ['CRM Salesforce', 'Zendesk', 'CSAT', 'NPS', 'Obsługa reklamacji', 'Angielski B2', 'Wielokanałowa obsługa'],
    },
    tips: [
      'Podaj wskaźniki CSAT, NPS lub czas pierwszej odpowiedzi.',
      'Wymień systemy CRM i ticketingowe, które znasz.',
      'Doświadczenie w wielojęzycznej obsłudze klienta jest dużym atutem.',
    ],
    faqs: [
      { q: 'Czy doradca klienta bez doświadczenia ma szansę?', a: 'Tak — firmy często szkolą od podstaw. Kluczowe są komunikatywność, cierpliwość i gotowość do uczenia się.' },
    ],
  },
  {
    slug: 'asystentka',
    icon: '🗂️',
    title: 'CV asystentki',
    titleGen: 'CV asystentki',
    intro: 'CV asystentki biura lub zarządu powinno podkreślać organizację, dyskrecję i umiejętność multitaskingu. Kluczowe są obsługa pakietu MS Office i znajomość języków obcych.',
    shouldContain: [
      'Obsługa MS Office (Word, Excel, PowerPoint, Outlook)',
      'Organizacja kalendarza i podróży służbowych',
      'Redagowanie korespondencji i protokołów',
      'Obsługa urządzeń biurowych i systemów DMS',
      'Znajomość języków obcych (angielski obowiązkowy)',
    ],
    example: {
      name: 'Justyna Kwiatkowska',
      position: 'Asystentka Zarządu',
      summary: 'Asystentka z 5-letnim doświadczeniem w obsłudze zarządu spółki notowanej na GPW. Organizuję podróże służbowe, przygotowuję prezentacje zarządcze i koordynuję korespondencję wewnętrzną i zewnętrzną.',
      experience: [{
        position: 'Asystentka Zarządu',
        company: 'Spółka ABC S.A.',
        dates: '2020 – obecnie',
        bullets: [
          'Prowadzę kalendarz Prezesa i 2 wiceprezesów spółki',
          'Organizuję podróże służbowe krajowe i zagraniczne (20+ rocznie)',
          'Przygotowuję materiały na posiedzenia zarządu i rady nadzorczej',
        ],
      }],
      skills: ['MS Office 365', 'SAP', 'Obsługa zarządu', 'Organizacja podróży', 'Angielski C1', 'Protokoły', 'DMS', 'Dyskrecja'],
    },
    tips: [
      'Podkreśl poziom organizacyjny i dyskrecję — to kluczowe cechy asystentki.',
      'Wymień obsługiwane systemy (SAP, ERP, narzędzia do zarządzania projektami).',
      'Znajomość angielskiego na poziomie min. B2 jest standardem.',
    ],
    faqs: [
      { q: 'Czy asystentka bez doświadczenia zarządczego znajdzie pracę?', a: 'Tak — wiele firm szuka asystentek bez doświadczenia w biurach administracyjnych, skąd można awansować do obsługi zarządu.' },
    ],
  },
  {
    slug: 'informatyk',
    icon: '🖥️',
    title: 'CV informatyka',
    titleGen: 'CV informatyka',
    intro: 'CV informatyka powinno pokazać specjalizację (sieci, systemy, helpdesk, bezpieczeństwo) i konkretne technologie. Certyfikaty Cisco, Microsoft lub CompTIA wyraźnie zwiększają wartość CV.',
    shouldContain: [
      'Specjalizacja: sieci, systemy, cyberbezpieczeństwo, helpdesk',
      'Technologie: Windows Server, Linux, Active Directory, VMware',
      'Certyfikaty: CCNA, CompTIA, AZ-900, ITIL',
      'Obsługa systemów ticketingowych (Jira, ServiceNow)',
      'Dokumentacja techniczna i procedury IT',
    ],
    example: {
      name: 'Artur Stępień',
      position: 'Informatyk / Administrator systemów',
      summary: 'Administrator systemów z 6-letnim doświadczeniem w środowiskach Windows Server i Linux. Posiadam certyfikat CCNA i AZ-900. Specjalizuję się w wirtualizacji (VMware, Hyper-V) i backupie.',
      experience: [{
        position: 'Administrator IT',
        company: 'Firma Produkcyjna PQR',
        dates: '2019 – obecnie',
        bullets: [
          'Administruję środowiskiem 120 stacji roboczych i 15 serwerów Windows/Linux',
          'Wdrożyłem backup Veeam i przetestowałem procedury DR (RTO 4h)',
          'Obsługuję helpdesk (2. linia wsparcia, 30 ticketów dziennie)',
        ],
      }],
      skills: ['Windows Server 2022', 'Linux', 'Active Directory', 'VMware', 'CCNA', 'Azure', 'Veeam', 'PowerShell'],
    },
    tips: [
      'Wymień certyfikaty — to najszybszy sposób na wyróżnienie CV informatyka.',
      'Podaj konkretne środowiska: liczba serwerów, stacji, użytkowników.',
      'Doświadczenie z chmurą (Azure, AWS) jest bardzo poszukiwane.',
    ],
    faqs: [
      { q: 'Czy informatyk bez certyfikatów znajdzie pracę?', a: 'Tak — szczególnie na helpdesku i w małych firmach. Certyfikaty CCNA czy AZ-900 przyspieszają jednak karierę i zwiększają wynagrodzenie.' },
    ],
  },
  {
    slug: 'tester-oprogramowania',
    icon: '🐞',
    title: 'CV testera oprogramowania',
    titleGen: 'CV testera oprogramowania',
    intro: 'CV testera oprogramowania powinno pokazać metodologie (manualne vs automatyzacja), narzędzia i doświadczenie z procesem QA w zespołach Agile. Certyfikat ISTQB jest bardzo ceniony.',
    shouldContain: [
      'Testy manualne i/lub automatyczne',
      'Narzędzia: Jira, TestRail, Selenium, Cypress, Postman',
      'Znajomość SQL i API (REST, SOAP)',
      'Certyfikat ISTQB (jeśli posiadasz)',
      'Doświadczenie w środowiskach Agile/Scrum',
    ],
    example: {
      name: 'Beata Czerwińska',
      position: 'QA Engineer / Tester oprogramowania',
      summary: 'Testerka z 4-letnim doświadczeniem w testowaniu aplikacji webowych i mobilnych. Posiadam certyfikat ISTQB Foundation. Specjalizuję się w automatyzacji testów w Selenium i Cypress.',
      experience: [{
        position: 'QA Engineer',
        company: 'Software House ABC',
        dates: '2021 – obecnie',
        bullets: [
          'Testuję aplikacje webowe i mobilne w sprintach 2-tygodniowych (Scrum)',
          'Pisałam testy automatyczne w Cypress, zwiększając pokrycie testami z 30% do 75%',
          'Raportowałam i śledziłam 300+ błędów w Jira w ciągu roku',
        ],
      }],
      skills: ['Testy manualne', 'Cypress', 'Selenium', 'Postman', 'Jira', 'SQL', 'ISTQB Foundation', 'Agile/Scrum', 'API testing'],
    },
    tips: [
      'ISTQB Foundation to standard — warto go zdobyć jeśli jeszcze nie masz.',
      'Podaj przykłady bugów krytycznych, które znalazłeś i opisz wpływ.',
      'Automatyzacja testów (Cypress, Selenium) jest bardzo poszukiwana.',
    ],
    faqs: [
      { q: 'Czy tester bez programowania znajdzie pracę?', a: 'Tak — testy manualne nie wymagają programowania. Automatyzacja to dodatkowy atut, ale nie zawsze wymaganie.' },
    ],
  },
  {
    slug: 'kierownik-projektu',
    icon: '📋',
    title: 'CV kierownika projektu',
    titleGen: 'CV kierownika projektu',
    intro: 'CV kierownika projektu musi pokazać wartość i złożoność prowadzonych projektów oraz metodologie (Agile, PRINCE2, PMI). Certyfikaty PMP lub PRINCE2 znacznie wyróżniają kandydata.',
    shouldContain: [
      'Metodologie: Agile, PRINCE2, PMI, PMBOK',
      'Wartość i skala prowadzonych projektów (budżet, zespół)',
      'Certyfikaty: PMP, PRINCE2, PSM, AgilePM',
      'Narzędzia: MS Project, Jira, Confluence, Monday',
      'Zarządzanie ryzykiem i interesariuszami',
    ],
    example: {
      name: 'Kamil Wojciechowski',
      position: 'Project Manager / Scrum Master',
      summary: 'Kierownik projektów IT z 7-letnim doświadczeniem. Posiadam certyfikaty PMP i PSM I. Prowadziłem projekty o budżetach do 5 mln PLN, zarządzając zespołami 10–25 osób.',
      experience: [{
        position: 'Senior Project Manager',
        company: 'Korporacja Technologiczna STU',
        dates: '2019 – obecnie',
        bullets: [
          'Prowadziłem 3 równoległe projekty IT o łącznym budżecie 8 mln PLN',
          'Dostarczyłem projekty na czas w 90% przypadków przy budżecie ±5%',
          'Zarządzałem zespołami 15–25 osób (programiści, UX, QA, BA)',
        ],
      }],
      skills: ['PMP', 'PSM I', 'Agile/Scrum', 'Jira', 'Confluence', 'MS Project', 'Zarządzanie ryzykiem', 'Stakeholders'],
    },
    tips: [
      'Podaj budżety i skalę projektów — to kluczowe informacje dla rekruterów.',
      'Certyfikaty PMP lub PRINCE2 znacznie wyróżniają CV.',
      'Podkreśl terminowość i realizację w budżecie.',
    ],
    faqs: [
      { q: 'Który certyfikat jest lepszy: PMP czy PRINCE2?', a: 'PMP jest bardziej rozpoznawany globalnie. PRINCE2 jest preferowany w projektach europejskich i publicznych. Warto mieć oba.' },
    ],
  },
  {
    slug: 'kosmetyczka',
    icon: '💅',
    title: 'CV kosmetyczki',
    titleGen: 'CV kosmetyczki',
    intro: 'CV kosmetyczki powinno pokazać posiadane certyfikaty, specjalizacje (manicure, pedicure, zabiegi twarzy) i obsługiwane marki produktów. Portfolio zdjęć przed/po to duży atut.',
    shouldContain: [
      'Certyfikaty: manicure, pedicure, zabiegi twarzy, depilacja',
      'Obsługiwane marki (Peggy Sage, OPI, Shellac)',
      'Rodzaje zabiegów: hybryda, żel, mezoterapia, peeling',
      'Obsługa klientek i budowanie lojalności',
      'Link do Instagram/portfolio (jeśli możliwe)',
    ],
    example: {
      name: 'Monika Kowalczyk',
      position: 'Kosmetyczka / Stylistka paznokci',
      summary: 'Kosmetyczka z 4-letnim doświadczeniem, specjalizująca się w manicure hybrydowym i zabiegach pielęgnacyjnych twarzy. Posiadam certyfikaty ze szkoleń OPI i Shellac. Stała baza 90 klientek.',
      experience: [{
        position: 'Kosmetyczka',
        company: 'Salon Urody Bella',
        dates: '2021 – obecnie',
        bullets: [
          'Wykonuję manicure hybrydowy, żelowy i zabiegi twarzy (20 klientek tygodniowo)',
          'Zbudowałam stałą bazę 90 lojalnych klientek',
          'Uczestniczyłam w szkoleniach OPI Academy i Shellac (2022, 2023)',
        ],
      }],
      skills: ['Manicure hybrydowy', 'Pedicure', 'Zabiegi twarzy', 'Depilacja', 'OPI', 'Shellac', 'Mezoterapia igłowa', 'Obsługa klienta'],
    },
    tips: [
      'Podaj certyfikaty ze szkoleń producentów — to weryfikowalne.',
      'Liczba stałych klientek świadczy o jakości pracy.',
      'Link do Instagram z portfolio prac to świetne uzupełnienie CV.',
    ],
    faqs: [
      { q: 'Czy kosmetyczka potrzebuje dyplomu?', a: 'W Polsce kosmetyczka nie musi mieć uprawnień państwowych, ale dyplom lub certyfikaty kursów zwiększają zaufanie klientów i pracodawców.' },
    ],
  },
  {
    slug: 'barista',
    icon: '☕',
    title: 'CV baristy',
    titleGen: 'CV baristy',
    intro: 'CV baristy powinno pokazać doświadczenie z espresso, znajomość metod parzenia kawy i obsługę sprzętu kawowego. Certyfikaty SCA lub barista courses to mocne wyróżniki.',
    shouldContain: [
      'Znajomość espresso, metod alternatywnych (V60, Chemex, Aeropress)',
      'Obsługa ekspresu ciśnieniowego i młynka',
      'Latte art i techniki spieniania mleka',
      'Certyfikaty SCA lub szkoły baristycznej',
      'Obsługa klienta i praca w tempie kawiarni',
    ],
    example: {
      name: 'Filip Nowak',
      position: 'Barista / Kawiarnia specialty',
      summary: 'Barista z 3-letnim doświadczeniem w kawiarniach specialty. Posiadam certyfikat SCA Barista Skills Foundation. Specjalizuję się w metodach alternatywnych i latte art.',
      experience: [{
        position: 'Barista',
        company: 'Kawiarnia The Barn Coffee — Warszawa',
        dates: '2022 – obecnie',
        bullets: [
          'Obsługuję 150–200 klientów dziennie w kawiarni specialty',
          'Przygotowuję kawy metodami espresso i alternatywnymi (V60, Chemex, Aeropress)',
          'Uczę nowych pracowników technik parzenia i standardów obsługi',
        ],
      }],
      skills: ['Espresso', 'V60', 'Chemex', 'Latte art', 'SCA Barista Skills', 'Obsługa klienta', 'Zarządzanie zapasami', 'Otwieranie/zamykanie'],
    },
    tips: [
      'Certyfikat SCA Barista Skills to standard w kawiarniach specialty.',
      'Doświadczenie w kawiarniach specialty jest bardziej cenione niż w sieciówkach.',
      'Latte art to bonus — podaj, jeśli potrafisz robić zaawansowane wzory.',
    ],
    faqs: [
      { q: 'Czy barista bez certyfikatów znajdzie pracę?', a: 'Tak — szczególnie w kawiarniach sieciowych. Certyfikaty SCA są wyróżnikiem w kawiarniach specialty.' },
    ],
  },
  {
    slug: 'doradca-finansowy',
    icon: '💰',
    title: 'CV doradcy finansowego',
    titleGen: 'CV doradcy finansowego',
    intro: 'CV doradcy finansowego musi pokazać certyfikaty (licencja KNF, CFP, CFA) i doświadczenie ze sprzedażą produktów finansowych. Kluczowa jest zgodność z regulacjami i wyniki sprzedażowe.',
    shouldContain: [
      'Licencja agenta ubezpieczeniowego lub pośrednika kredytowego',
      'Certyfikaty: CFP, CFA, EFA, licencja KNF',
      'Sprzedaż: fundusze, ubezpieczenia, kredyty, lokaty',
      'Wyniki sprzedażowe (wartość portfela, liczba klientów)',
      'Znajomość regulacji MiFID II i PRIIP',
    ],
    example: {
      name: 'Katarzyna Brzezińska',
      position: 'Doradca Finansowy / Wealth Manager',
      summary: 'Doradca finansowy z 7-letnim doświadczeniem w zarządzaniu portfelami klientów zamożnych. Posiadam certyfikat EFA i licencję KNF. Zarządzam portfelem 120 klientów o łącznych aktywach 15 mln PLN.',
      experience: [{
        position: 'Doradca Finansowy',
        company: 'Bank Inwestycyjny VWX',
        dates: '2018 – obecnie',
        bullets: [
          'Zarządzam portfelem 120 klientów (segment Private Banking, aktywa >125 000 PLN)',
          'Realizuję 130% planu sprzedażowego rok do roku',
          'Kompleksowo doradzam w zakresie inwestycji, ubezpieczeń i planowania emerytalnego',
        ],
      }],
      skills: ['Licencja KNF', 'EFA', 'MiFID II', 'Fundusze inwestycyjne', 'Ubezpieczenia', 'Planowanie emerytalne', 'Bloomberg', 'CRM'],
    },
    tips: [
      'Licencje i certyfikaty KNF, EFA, CFP są obowiązkowe w CV doradcy.',
      'Podaj wartość zarządzanego portfela lub liczbę klientów.',
      'Znajomość regulacji MiFID II jest wymagana na stanowiskach inwestycyjnych.',
    ],
    faqs: [
      { q: 'Czy doradca finansowy musi mieć licencję KNF?', a: 'Tak, do oferowania produktów inwestycyjnych wymagana jest licencja KNF. Dla ubezpieczeń niezbędna jest licencja agenta ubezpieczeniowego.' },
    ],
  },
  {
    slug: 'student',
    icon: '🎓',
    title: 'CV studenta',
    titleGen: 'CV studenta',
    intro: 'CV studenta bez doświadczenia powinno podkreślać projekty uczelniane, wolontariat, staże i umiejętności miękkie. Rekruterzy szukają potencjału, motywacji i gotowości do nauki.',
    shouldContain: [
      'Wykształcenie: kierunek, uczelnia, rok studiów, GPA (jeśli dobre)',
      'Staże i praktyki studenckie',
      'Projekty uczelniane i pozauczelniane',
      'Wolontariat i aktywność w organizacjach studenckich',
      'Umiejętności: MS Office, języki, narzędzia branżowe',
    ],
    example: {
      name: 'Aleksander Wojtyla',
      position: 'Student Informatyki — szuka stażu',
      summary: 'Student III roku Informatyki (Politechnika Warszawska). Uczestniczę w kołach naukowych, tworzę projekty webowe w React i interesuję się Machine Learning. Szukam stażu w dziale IT lub software development.',
      experience: [{
        position: 'Stażysta IT',
        company: 'Startup FinTech ABC (praktyki studenckie)',
        dates: '2024 (3 miesiące)',
        bullets: [
          'Budowałem komponenty frontendu w React.js pod nadzorem seniora',
          'Uczestniczyłem w codziennych standupach w metodyce Scrum',
          'Naprawiłem 15 bugów w systemie z raportowanymi błędami UX',
        ],
      }],
      skills: ['React', 'Python', 'JavaScript', 'Git', 'SQL', 'MS Excel', 'Angielski C1', 'Figma (podstawy)', 'Jira'],
    },
    tips: [
      'Projekty uczelniane i własne projekty githubowe zastępują brak doświadczenia.',
      'Podaj GPA lub wyróżnienia naukowe, jeśli są dobre.',
      'Wolontariat i działalność w kołach naukowych pokazują inicjatywę.',
      'Staże — nawet krótkie — bardzo poprawiają CV studenta.',
    ],
    faqs: [
      { q: 'Jak napisać CV studenta bez doświadczenia?', a: 'Postaw na projekty uczelniane, staże, wolontariat i umiejętności. Napisz krótkie podsumowanie, które pokazuje Twoją motywację i kierunek rozwoju.' },
      { q: 'Czy student powinien pisać o ocenach w CV?', a: 'Tylko jeśli GPA jest dobre (4.0+ lub wyróżnienie). Dla pracodawców ważniejsze są projekty i staże niż oceny.' },
    ],
  },
]

export function getWzor(slug: string): WzorCV | undefined {
  return WZORY.find(w => w.slug === slug)
}
